name: Version Management

on:
    push:
        branches: [main]

jobs:
    version:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'chore(release):')"
        permissions:
            contents: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Git config
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Determine version bump
              id: bump
              run: |
                  COMMIT_MSG=$(git log -1 --pretty=%B)
                  if echo "$COMMIT_MSG" | grep -q "^BREAKING CHANGE"; then
                    echo "type=major" >> $GITHUB_OUTPUT
                  elif echo "$COMMIT_MSG" | grep -q "^feat"; then
                    echo "type=minor" >> $GITHUB_OUTPUT
                  else
                    echo "type=patch" >> $GITHUB_OUTPUT
                  fi

            - name: Bump version
              run: |
                  VERSION_TYPE=${{ steps.bump.outputs.type }}
                  yarn version:$VERSION_TYPE

            - name: Push changes
              run: |
                  git push
                  git push --tags
